### ISSUE TITLE
can we use dresscode dataset?

### ISSUE THREAD

**Issue by sudip550** [ARajgor/cp-vton-plus#7]
i have few questions??

1) can we use dresscode dataset to train model? or is there any model which is trained on dresscode.

2) can we train 20k steps in one day and start training from 20k after some time.

3) i want to use it with high quality custom images... how much steps i need to train, then it will work with custom images.

**Comment by ARajgor** [comment]
I don't know about dresscode dataset but they have results on CP-VTON+ as in their repo, so I guess you can train. 

for your second question, you can do that but things got complicated. You have to save the checkpoints and load from there, shuffle the images, it tedious also result will not be that accurate.

high quality means more pixels, Let imagine an image size is 1024 x 1024 x 3 now, the training set has 14K images so that is a lot of tensors. it's not an efficient way. It may give you better results but training will cost you significantly. also, inference time also increases. You can do one thing, after getting the result pass it on to image scaling GANs models. it upscale the image from 192 x 256 to 1024 x 1024 but do your own research for that.
